#EXTM3U
#EXTINF:-1,欢笑剧场4K
https://live.goodiptv.club/api/cqyx.php?id=hxjc_4K
#EXTINF:-1,CCTV-4K
https://live.goodiptv.club/api/cqyx.php?id=CCTV4K
#EXTINF:-1,CCTV16-4K
https://live.goodiptv.club/api/cqyx.php?id=CCTV16_4K
#EXTINF:-1,4K60PSDR-H264-AAC测试
http://159.75.85.63:5680/d/ad/h264/playad.m3u8
#EXTINF:-1,4K60PHLG-HEVC-EAC3测试
http://159.75.85.63:5680/d/ad/playad.m3u8
#EXTINF:-1,CCTV1综合高清
https://live.goodiptv.club/api/cqyx.php?id=cctv1HD
#EXTINF:-1,CCTV2财经高清
https://live.goodiptv.club/api/cqyx.php?id=cctv2HD
#EXTINF:-1,CCTV3综艺高清
https://live.goodiptv.club/api/cqyx.php?id=cctv3HD
#EXTINF:-1,CCTV4中文国际高清
https://live.goodiptv.club/api/cqyx.php?id=cctv4HD
#EXTINF:-1,CCTV5体育高清
https://live.goodiptv.club/api/cqyx.php?id=cctv5HD
#EXTINF:-1,CCTV5P高清
https://live.goodiptv.club/api/cqyx.php?id=cctv5SportHD
#EXTINF:-1,CCTV6电影高清
https://live.goodiptv.club/api/cqyx.php?id=cctv6HD
#EXTINF:-1,CCTV7国防军事高清
https://live.goodiptv.club/api/cqyx.php?id=cctv7HD
#EXTINF:-1,CCTV8电视剧高清
https://live.goodiptv.club/api/cqyx.php?id=cctv8HD
#EXTINF:-1,CCTV9纪录高清
https://live.goodiptv.club/api/cqyx.php?id=cctv9HD
#EXTINF:-1,CCTV10科教高清
https://live.goodiptv.club/api/cqyx.php?id=cctv10HD
#EXTINF:-1,CCTV11戏曲高清
https://live.goodiptv.club/api/cqyx.php?id=cctv11HD
#EXTINF:-1,CCTV12社会与法高清
https://live.goodiptv.club/api/cqyx.php?id=cctv12HD
#EXTINF:-1,CCTV13新闻高清
https://live.goodiptv.club/api/cqyx.php?id=CCTVNewsHD
#EXTINF:-1,CCTV14少儿高清
https://live.goodiptv.club/api/cqyx.php?id=cctvseHD
#EXTINF:-1,CCTV15音乐高清
https://live.goodiptv.club/api/cqyx.php?id=cctv15HD
#EXTINF:-1,CCTV16奥林匹克高清
https://live.goodiptv.club/api/cqyx.php?id=cctv16HD
#EXTINF:-1,CCTV17农业农村高清
https://live.goodiptv.club/api/cqyx.php?id=cctv17HD
#EXTINF:-1,重庆卫视高清
https://live.goodiptv.club/api/cqyx.php?id=chongqingHD
#EXTINF:-1,江苏卫视高清
https://live.goodiptv.club/api/cqyx.php?id=jiangsuHD
#EXTINF:-1,北京卫视高清
https://live.goodiptv.club/api/cqyx.php?id=beijingHD
#EXTINF:-1,浙江卫视高清
https://live.goodiptv.club/api/cqyx.php?id=zhejiangHD
#EXTINF:-1,东方卫视高清
https://live.goodiptv.club/api/cqyx.php?id=shanghaiHD
#EXTINF:-1,深圳卫视高清
https://live.goodiptv.club/api/cqyx.php?id=shenzhenHD
#EXTINF:-1,辽宁卫视高清
https://live.goodiptv.club/api/cqyx.php?id=liaoningHD
#EXTINF:-1,天津卫视高清
https://live.goodiptv.club/api/cqyx.php?id=tianjinHD
#EXTINF:-1,贵州卫视高清
https://live.goodiptv.club/api/cqyx.php?id=guizhouHD
#EXTINF:-1,四川卫视高清
https://live.goodiptv.club/api/cqyx.php?id=sichuanHD
#EXTINF:-1,云南卫视高清
https://live.goodiptv.club/api/cqyx.php?id=yunnanSD
#EXTINF:-1,东南卫视高清
https://live.goodiptv.club/api/cqyx.php?id=dongnanHD
#EXTINF:-1,黑龙江卫视高清
https://live.goodiptv.club/api/cqyx.php?id=heilongjiangHD
#EXTINF:-1,安徽卫视高清
https://live.goodiptv.club/api/cqyx.php?id=anhuiSD
#EXTINF:-1,河北卫视高清
https://live.goodiptv.club/api/cqyx.php?id=hebeiSD
#EXTINF:-1,江西卫视高清
https://live.goodiptv.club/api/cqyx.php?id=jiangxiHD
#EXTINF:-1,湖北卫视高清
https://live.goodiptv.club/api/cqyx.php?id=hubeiSD
#EXTINF:-1,海南卫视高清
https://live.goodiptv.club/api/cqyx.php?id=hainanSD
#EXTINF:-1,吉林卫视高清
https://live.goodiptv.club/api/cqyx.php?id=jilinHD
#EXTINF:-1,广西卫视高清
https://live.goodiptv.club/api/cqyx.php?id=guangxiHD
#EXTINF:-1,内蒙古卫视
https://live.goodiptv.club/api/cqyx.php?id=neimengkuSD
#EXTINF:-1,湖南卫视高清
https://live.goodiptv.club/api/cqyx.php?id=hunanHD
#EXTINF:-1,广东卫视高清
https://live.goodiptv.club/api/cqyx.php?id=guangdongHD
#EXTINF:-1,河南卫视高清
https://live.goodiptv.club/api/cqyx.php?id=henanHD
#EXTINF:-1,山西卫视
https://live.goodiptv.club/api/cqyx.php?id=shanxiSD
#EXTINF:-1,兵团卫视
https://live.goodiptv.club/api/cqyx.php?id=bingtuanSD
#EXTINF:-1,宁夏卫视
https://live.goodiptv.club/api/cqyx.php?id=ningxia
#EXTINF:-1,北京卡酷少儿
https://live.goodiptv.club/api/cqyx.php?id=bjkakuSD
#EXTINF:-1,金鹰卡通高清
https://live.goodiptv.club/api/cqyx.php?id=jinyingSD
#EXTINF:-1,三沙卫视
https://live.goodiptv.club/api/cqyx.php?id=sanshaSD
#EXTINF:-1,青海卫视
https://live.goodiptv.club/api/cqyx.php?id=qinghaiSD
#EXTINF:-1,中国天气
https://live.goodiptv.club/api/cqyx.php?id=tianqiSD
#EXTINF:-1,北京纪实科教高清
https://live.goodiptv.club/api/cqyx.php?id=bjayjsSD
#EXTINF:-1,山东教育卫视
https://live.goodiptv.club/api/cqyx.php?id=sdjiaoyuSD
#EXTINF:-1,新疆卫视
https://live.goodiptv.club/api/cqyx.php?id=xinjiangSD
#EXTINF:-1,西藏卫视
https://live.goodiptv.club/api/cqyx.php?id=xizangSD
#EXTINF:-1,CGTN
https://live.goodiptv.club/api/cqyx.php?id=cgtnSD
#EXTINF:-1,CETV-1
https://live.goodiptv.club/api/cqyx.php?id=cetv-1SD
#EXTINF:-1,CETV-4
https://live.goodiptv.club/api/cqyx.php?id=cetv-4SD
#EXTINF:-1,生活时尚
https://live.goodiptv.club/api/cqyx.php?id=shenghuo
#EXTINF:-1,百姓健康
https://live.goodiptv.club/api/cqyx.php?id=jiankangSD
#EXTINF:-1,快乐垂钓高清
https://live.goodiptv.club/api/cqyx.php?id=klcdHD
#EXTINF:-1,第一剧场高清
https://live.goodiptv.club/api/cqyx.php?id=diyijuchangHD
#EXTINF:-1,都市剧场高清
https://live.goodiptv.club/api/cqyx.php?id=dsjcHD
#EXTINF:-1,动漫秀场高清
https://live.goodiptv.club/api/cqyx.php?id=dmxcHD
#EXTINF:-1,魅力足球高清
https://live.goodiptv.club/api/cqyx.php?id=mlzqHD
#EXTINF:-1,风云剧场高清
https://live.goodiptv.club/api/cqyx.php?id=fyjcHD
#EXTINF:-1,求索纪录高清
https://live.goodiptv.club/api/cqyx.php?id=qsjlHD
#EXTINF:-1,兵器科技高清
https://live.goodiptv.club/api/cqyx.php?id=bqkjHD
#EXTINF:-1,游戏风云高清
https://live.goodiptv.club/api/cqyx.php?id=yxfyHD
#EXTINF:-1,怀旧剧场高清
https://live.goodiptv.club/api/cqyx.php?id=hjjcHD
#EXTINF:-1,风云音乐高清
https://live.goodiptv.club/api/cqyx.php?id=fyyyHD
#EXTINF:-1,央视台球高清
https://live.goodiptv.club/api/cqyx.php?id=ystqHD
#EXTINF:-1,风云足球高清
https://live.goodiptv.club/api/cqyx.php?id=fyzqHD
#EXTINF:-1,央视文化精品高清
https://live.goodiptv.club/api/cqyx.php?id=yswhHD
#EXTINF:-1,高尔夫网球高清
https://live.goodiptv.club/api/cqyx.php?id=golfHD
#EXTINF:-1,早期教育高清
https://live.goodiptv.club/api/cqyx.php?id=zaojiaoHD
#EXTINF:-1,重庆新闻高清
https://live.goodiptv.club/api/cqyx.php?id=CQTVNewsHD
#EXTINF:-1,重庆影视高清
https://live.goodiptv.club/api/cqyx.php?id=cqyingshiHD
#EXTINF:-1,重庆社会与法高清
https://live.goodiptv.club/api/cqyx.php?id=CQTVTrendyHD
#EXTINF:-1,重庆时尚生活高清
https://live.goodiptv.club/api/cqyx.php?id=cqssgwHD
#EXTINF:-1,重庆文体娱乐高清
https://live.goodiptv.club/api/cqyx.php?id=cqwtylHD
#EXTINF:-1,重庆新农村高清
https://live.goodiptv.club/api/cqyx.php?id=cqggncHD
#EXTINF:-1,重庆少儿高清
https://live.goodiptv.club/api/cqyx.php?id=cqseHD
#EXTINF:-1,重庆科教高清
https://live.goodiptv.club/api/cqyx.php?id=CQTVkejiaoHD
#EXTINF:-1,爱看导视高清
https://live.goodiptv.club/api/cqyx.php?id=aikanHD
#EXTINF:-1,重庆汽摩高清
https://live.goodiptv.club/api/cqyx.php?id=cqcarSD
#EXTINF:-1,重庆移动高清
https://live.goodiptv.club/api/cqyx.php?id=mryyHD
#EXTINF:-1,重广融媒
https://live.goodiptv.club/api/cqyx.php?id=cqrongmei
#EXTINF:-1,优购物
https://live.goodiptv.club/api/cqyx.php?id=yougouwu
#EXTINF:-1,家家购物
https://live.goodiptv.club/api/cqyx.php?id=jjgw
#EXTINF:-1,风尚购物
https://live.goodiptv.club/api/cqyx.php?id=fsgw
#EXTINF:-1,聚鲨环球精选
https://live.goodiptv.club/api/cqyx.php?id=jusha
#EXTINF:-1,中视购物
https://live.goodiptv.club/api/cqyx.php?id=ysgw
#EXTINF:-1,家有购物
https://live.goodiptv.club/api/cqyx.php?id=jygw
#EXTINF:-1,央广购物
https://live.goodiptv.club/api/cqyx.php?id=yggw
#EXTINF:-1,东方财经高清
https://live.goodiptv.club/api/cqyx.php?id=dfcj
#EXTINF:-1,证券服务
https://live.goodiptv.club/api/cqyx.php?id=jiazheng
#EXTINF:-1,书画
https://live.goodiptv.club/api/cqyx.php?id=shuhua
#EXTINF:-1,新动漫
https://live.goodiptv.club/api/cqyx.php?id=dongman
#EXTINF:-1,国学频道
https://live.goodiptv.club/api/cqyx.php?id=guoxue
#EXTINF:-1,优优宝贝
https://live.goodiptv.club/api/cqyx.php?id=youxi
#EXTINF:-1,中华特产
https://live.goodiptv.club/api/cqyx.php?id=techan
#EXTINF:-1,环球奇观
https://live.goodiptv.club/api/cqyx.php?id=car
#EXTINF:-1,生态环境
https://live.goodiptv.club/api/cqyx.php?id=shengtai
#EXTINF:-1,四海钓鱼
https://live.goodiptv.club/api/cqyx.php?id=diaoyu
#EXTINF:-1,发现之旅
https://live.goodiptv.club/api/cqyx.php?id=faxian
#EXTINF:-1,车迷
https://live.goodiptv.club/api/cqyx.php?id=doxtv
#EXTINF:-1,法治天地
https://live.goodiptv.club/api/cqyx.php?id=fazhi
#EXTINF:-1,金色学堂
https://live.goodiptv.club/api/cqyx.php?id=jinse
#EXTINF:-1,收藏天下
https://live.goodiptv.club/api/cqyx.php?id=soucang
#EXTINF:-1,财富天下
https://live.goodiptv.club/api/cqyx.php?id=caifu
#EXTINF:-1,女性时尚
https://live.goodiptv.club/api/cqyx.php?id=nvxing
#EXTINF:-1,中学生
https://live.goodiptv.club/api/cqyx.php?id=qicai
#EXTINF:-1,天元围棋
https://live.goodiptv.club/api/cqyx.php?id=weiqi
#EXTINF:-1,先锋乒羽
https://live.goodiptv.club/api/cqyx.php?id=xianfeng
#EXTINF:-1,环球旅游
https://live.goodiptv.club/api/cqyx.php?id=huanqiulvyou
#EXTINF:-1,老故事
https://live.goodiptv.club/api/cqyx.php?id=gushi
#EXTINF:-1,摄影频道
https://live.goodiptv.club/api/cqyx.php?id=sheying
#EXTINF:-1,靓妆
https://live.goodiptv.club/api/cqyx.php?id=liang
